version: "3.3"
services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - my_app:/var/lib/postgresql/data

volumes:
  my_app:

networks:
  my_network:
